url: http://mkremins.github.io

defaults:
  -
    scope:
      path: "" # everything
      type: posts
    values:
      layout: default
      permalink: /blog/:slug/
  -
    scope:
      path: "" # everything
      type: pages
    values:
      layout: default
  -
    scope:
      path: "" # everything
      type: drafts
    values:
      layout: default
      permalink: /blog/:slug/
